name: isthihaaru
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  screenshot: ^3.0.0
  path_provider: ^2.1.4
  image: ^4.2.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.0

icons_launcher:
  platforms:
    android:
      enable: true
      image_path: "assets/icons/icon.png"
      adaptive_background_image: "assets/icons/adaptive_back.png"
      adaptive_foreground_image: "assets/icons/adaptive_front.png"

flutter:
  uses-material-design: true

  fonts:
    - family: MVAWaheed
      fonts:
        - asset: fonts/MVAWaheed.ttf
    - family: aammufkF
      fonts:
        - asset: fonts/aammufkF.ttf
    - family: AKRasmee
      fonts:
        - asset: fonts/AK Rasmee.ttf
    - family: FarumaV2
      fonts:
        - asset: fonts/Faruma V2.0.ttf
    - family: MageyHuseynu-Regular
      fonts:
        - asset: fonts/MageyHuseynu-Regular.ttf
    - family: MVBodu
      fonts:
        - asset: fonts/MV Bodu.otf
    - family: MvGaaLhohi
      fonts:
        - asset: fonts/Mv Gaa Lhohi.ttf
    - family: MvIzyanboduakuru
      fonts:
        - asset: fonts/Mv Izyan bodu akuru.ttf
    - family: MvIzyanSuruhee
      fonts:
        - asset: fonts/Mv Izyan Suruhee .ttf
    - family: Mvsuruhee
      fonts:
        - asset: fonts/Mv suruhee.ttf
    - family: MvThakurufaanu
      fonts:
        - asset: fonts/Mv Thakurufaanu.ttf
    - family: Mvizyanboduakuru3D-Bold
      fonts:
        - asset: fonts/Mvizyanboduakuru3D-Bold.ttf
    - family: Mvlhohibold
      fonts:
        - asset: fonts/Mvlhohi bold.ttf
    - family: mvtypewritersb_v1
      fonts:
        - asset: fonts/mvtypewritersb_v1.1.ttf
    - family: Randhoo_reg_hinted
      fonts:
        - asset: fonts/Randhoo_reg_hinted.ttf
